// split_test_groups discovers every Go module in the repository and emits a
// CI matrix, one entry per module, so tests can be run in parallel GitHub
// Actions jobs.
//
// Outputs a JSON object suitable for GitHub Actions fromJson:
//
//	{"include": [
//	  {"name":"core",        "dir":".",                         "timeout_minutes":10},
//	  {"name":"postgres",    "dir":"./applications/postgres",   "timeout_minutes":25},
//	  {"name":"clickhouse",  "dir":"./applications/clickhouse", "timeout_minutes":25},
//	  ...
//	]}
//
// Each job changes into its module directory and runs `go test ./...`. The
// go.work (generated by `make work`) is expected to be present so modules
// resolve the core and sibling application modules locally without requiring
// a published core tag.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type group struct {
	Name           string `json:"name"`
	Dir            string `json:"dir"`
	TimeoutMinutes int    `json:"timeout_minutes"`
}

type matrix struct {
	Include []group `json:"include"`
}

func main() {
	if len(os.Args) > 1 {
		fmt.Fprintf(os.Stderr, "Usage: %s\nNo arguments accepted.\n", os.Args[0])
		os.Exit(1)
	}

	modules := discoverModules()

	var include []group
	for _, m := range modules {
		name := moduleName(m) // "." → "core", else the application name
		timeout := 10
		if name != "core" {
			timeout = 25
		}
		include = append(include, group{
			Name:           name,
			Dir:            m,
			TimeoutMinutes: timeout,
		})
	}

	if err := json.NewEncoder(os.Stdout).Encode(matrix{Include: include}); err != nil {
		fmt.Fprintf(os.Stderr, "error encoding JSON: %v\n", err)
		os.Exit(1)
	}
}

// discoverModules finds every directory that contains a go.mod, starting with
// the root module ".". Sub-modules (applications/<name>) are sorted by name.
func discoverModules() []string {
	var mods []string
	err := filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() && info.Name() == "go.mod" {
			// go.mod is a file, so this branch is never hit for go.mod;
			// handled below.
			return nil
		}
		if info.IsDir() && strings.HasPrefix(info.Name(), ".") && info.Name() != "." {
			return filepath.SkipDir
		}
		if info.Name() == "go.mod" && !info.IsDir() {
			dir := filepath.Dir(path)
			if dir == "." {
				mods = append(mods, ".")
			} else {
				mods = append(mods, "./"+dir)
			}
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error walking for go.mod files: %v\n", err)
		os.Exit(1)
	}

	// Ensure "." is first, then sort the rest.
	var rest []string
	for _, m := range mods {
		if m != "." {
			rest = append(rest, m)
		}
	}
	sort.Strings(rest)
	return append([]string{"."}, rest...)
}

// moduleName returns the CI group name for a module dir: "." → "core",
// otherwise the application directory name.
func moduleName(dir string) string {
	if dir == "." {
		return "core"
	}
	return filepath.Base(dir)
}
